# Generated by Django 4.2.4 on 2023-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndedGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
                ('leagues', models.CharField(max_length=200)),
                ('matchDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LaterGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
                ('leagues', models.CharField(max_length=200)),
                ('matchDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
                ('leagues', models.CharField(max_length=200)),
                ('matchDate', models.DateTimeField()),
            ],
        ),
    ]
