# Generated by Django 4.2.4 on 2023-09-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
                ('leagues', models.CharField(max_length=200)),
                ('matchDate', models.DateTimeField()),
                ('homeLogo', models.CharField(max_length=500)),
                ('awayLogo', models.CharField(max_length=500)),
                ('match_type', models.CharField(choices=[('LIVE', 'live'), ('ENDED', 'ended'), ('LATER', 'later')], max_length=5)),
            ],
        ),
    ]
